// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7g2rJvBDrrnQGIlf2wDRLHmIdScJdbSU',
    appId: '1:791858627170:web:7cbdd85b78baacd9dec73b',
    messagingSenderId: '791858627170',
    projectId: 'moody-20fa4',
    authDomain: 'moody-20fa4.firebaseapp.com',
    storageBucket: 'moody-20fa4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxf1ZrQDsjyITzZU4HdbBT-Y3PiT6v9xY',
    appId: '1:791858627170:android:60b3b9c9daacab2ddec73b',
    messagingSenderId: '791858627170',
    projectId: 'moody-20fa4',
    storageBucket: 'moody-20fa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd24tBwr88CRl1KMidfZXF-Omi52b2xN8',
    appId: '1:791858627170:ios:9c7988b6dc8a9d3edec73b',
    messagingSenderId: '791858627170',
    projectId: 'moody-20fa4',
    storageBucket: 'moody-20fa4.firebasestorage.app',
    iosBundleId: 'com.example.activity1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd24tBwr88CRl1KMidfZXF-Omi52b2xN8',
    appId: '1:791858627170:ios:9c7988b6dc8a9d3edec73b',
    messagingSenderId: '791858627170',
    projectId: 'moody-20fa4',
    storageBucket: 'moody-20fa4.firebasestorage.app',
    iosBundleId: 'com.example.activity1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7g2rJvBDrrnQGIlf2wDRLHmIdScJdbSU',
    appId: '1:791858627170:web:e0befdf07ceb7011dec73b',
    messagingSenderId: '791858627170',
    projectId: 'moody-20fa4',
    authDomain: 'moody-20fa4.firebaseapp.com',
    storageBucket: 'moody-20fa4.firebasestorage.app',
  );
}
